---
- name: Verify that required parameters are set
  assert:
    that:
      - '{{ item }} is defined'
      - '{{ item }} | length > 0'
  with_items:
    - cloudinit_fqdn
    - kvm_image_size
    - kvm_download_url
    - kvm_dist_release_date
    - kvm_distname
    - kvm_image_name
    - kvm_cloudimage_kvm_url
    - kvm_cloudimage_kvm_checksum
    - kvm_image_path
    - cloudinit_rendering
...
